enum instr_type {
	IT_reg,
	IT_imm,
	IT_imma,
	IT_immu,
	IT_code,
	IT_jump,
	IT_regf,
	IT_nop
};

struct instr_def{
	int type;
	char name[32];
	char para[128];
} instrs[] = {
	{IT_reg, "ADD", "$rd, $rs, $rt"},
	{IT_imm, "ADDI", "$rt, $rs, #im"},
	{IT_imm, "ADDIU", "$rt, $rs, #im"},
	{IT_reg, "ADDU", "$rd, $rs, $rt"},
	{IT_reg, "AND", "$rd, $rs, $rd"},
	{IT_immu, "ANDI", "$rt, $rs, %im"},
	{IT_imma, "BEQ", "$rs, $rt, &im"},
	{IT_imma, "BEQL", "$rs, $rt, &im"},
	{IT_imma, "BGEZ", "$rs, &im"},
	{IT_imma, "BGEZAL", "$rs, &im"},
	{IT_imma, "BGEZALL", "$rs, &im"},
	{IT_imma, "BGEZL", "$rs, &im"},
	{IT_imma, "BGTZ", "$rs, &im"},
	{IT_imma, "BGTZL", "$rs, &im"},
	{IT_imma, "BLEZ", "$rs, &im"},
	{IT_imma, "BLEZL", "$rs, &im"},
	{IT_imma, "BLTZ", "$rs, &im"},
	{IT_imma, "BLTZAL", "$rs, &im"},
	{IT_imma, "BLTZALL", "$rs, &im"},
	{IT_imma, "BLTZL", "$rs, &im"},
	{IT_imma, "BNE", "$rs, $rt, &im"},
	{IT_imma, "BNEL", "$rs, $rt, &im"},
	{IT_code, "BREAK", "!im"},
	{IT_reg, "DADD", "$rd, $rs, $rt"},
	{IT_imm, "DADDI", "$rt, $rs, #im"},
	{IT_imm, "DADDIU", "$rt, $rs, #im"},
	{IT_imm, "DADDU", "$rd, $rs, $rt"},
	{IT_reg, "DIV", "$rs, $rt"},
	{IT_reg, "DIVU", "$rs, $rt"},
	{IT_reg, "DSLL", "$rd, $rt, %sa"},
	{IT_reg, "DSLL32", "$rd, $rt, %sa"},
	{IT_reg, "DSLLV", "$rd, $rt, $rs"},
	{IT_reg, "DSRA", "$rd, $rt, %sa"},
	{IT_reg, "DSRA32", "$rd, $rt, %sa"},
	{IT_reg, "DSRAV", "$rd, $rt, $rs"},
	{IT_reg, "DSRL", "$rd, $rt, %sa"},
	{IT_reg, "DSRL32", "$rd, $rt, %sa"},
	{IT_reg, "DSRLV", "$rd, $rt, $rs"},
	{IT_reg, "DSUB", "$rd, $rs, $rt"},
	{IT_reg, "DSUBU", "$rd, $rs, $rt"},
	{IT_jump, "J", "*im"},
	{IT_jump, "JAL", "*im"},
	{IT_reg, "JALR", "$rs, $rd"},
	{IT_reg, "JR", "$rs"},
	{IT_imm, "LB", "$rt, #im($rs)"},
	{IT_imm, "LBU", "$rt, #im($rs)"},
	{IT_imm, "LD", "$rt, #im($rs)"},
	{IT_imm, "LDL", "$rt, #im($rs)"},
	{IT_imm, "LDR", "$rt, #im($rs)"},
	{IT_imm, "LH", "$rt, #im($rs)"},
	{IT_imm, "LHU", "$rt, #im($rs)"},
	{IT_immu, "LUI", "$rt, %im"},
	{IT_imm, "LW", "$rt, #im($rs)"},
	{IT_imm, "LWL", "$rt, #im($rs)"},
	{IT_imm, "LWR", "$rt, #im($rs)"},
	{IT_imm, "LWU", "$rt, #im($rs)"},
	{IT_reg, "MFHI", "$rd"},
	{IT_reg, "MFLO", "$rd"},
	{IT_reg, "MOVN", "$rd, $rs, $rt"},
	{IT_reg, "MOVZ", "$rd, $rs, $rt"},
	{IT_reg, "MTHI", "$rs"},
	{IT_reg, "MTLO", "$rs"},
	{IT_reg, "MULT", "$rd, $rs, $rt"},
	{IT_reg, "MULTU", "$rs, $rt"},
	{IT_reg, "NOR", "$rd, $rs, $rt"},
	{IT_reg, "OR", "$rd, $rs, $rt"},
	{IT_immu, "ORI", "$rt, $rs, %im"},
	{IT_imm, "PREF", "$rt, #im($rs)"},
	{IT_imm, "SB", "$rt, #im($rs)"},
	{IT_imm, "SD", "$rt, #im($rs)"},
	{IT_imm, "SDL", "$rt, #im($rs)"},
	{IT_imm, "SDR", "$rt, #im($rs)"},
	{IT_imm, "SH", "$rt, #im($rs)"},
	{IT_reg, "SLL", "$rd, $rt, %sa"},
	{IT_reg, "SLLV", "$rd, $rt, $rs"},
	{IT_reg, "SLT", "$rd, $rt, $rs"},
	{IT_imm, "SLTI", "$rt, $rs, #im"},
	{IT_immu, "SLTIU", "$rt, $rs, %im"},
	{IT_reg, "SLTU", "$rd, $rt, $rs"},
	{IT_reg, "SRA", "$rd, $rt, %sa"},
	{IT_reg, "SRAV", "$rd, $rt, $rs"},
	{IT_reg, "SRL", "$rd, $rt, %sa"},
	{IT_reg, "SRLV", "$rd, $rt, $rs"},
	{IT_reg, "SUB", "$rd, $rt, $rs"},
	{IT_reg, "SUBU", "$rd, $rt, $rs"},
	{IT_imm, "SW", "$rt, #im($rs)"},
	{IT_imm, "SWL", "$rt, #im($rs)"},
	{IT_imm, "SWR", "$rt, #im($rs)"},
	{IT_reg, "SYNC", "!sa"},
	{IT_code, "SYSCALL", "!im"},
	{IT_reg, "TEQ", "$rs, $rt"},
	{IT_imm, "TEQI", "$rs, #im"},
	{IT_reg, "TGE", "$rs, $rt"},
	{IT_imm, "TGEI", "$rs, #im"},
	{IT_imm, "TGEIU", "$rs, #im"},
	{IT_reg, "TGEU", "$rs, $rt"},
	{IT_reg, "TLT", "$rs, $rt"},
	{IT_imm, "TLTI", "$rs, #im"},
	{IT_imm, "TLTIU", "$rs, #im"},
	{IT_reg, "TLTU", "$rs, $rt"},
	{IT_reg, "TNE", "$rs, $rt"},
	{IT_imm, "TNEI", "$rs, #im"},
	{IT_reg, "XOR", "$rd, $rs, $rt"},
	{IT_immu, "XORI", "$rs, $rt, %im"},
	{IT_reg, "DIV1", "$rs, $rt"},
	{IT_reg, "DIVU1", "$rs, $rt"},
	{IT_imm, "LQ", "$rt, #im($rs)"},
	{IT_reg, "MADD", "$rd, $rs, $rt"},
	{IT_reg, "MADD1", "$rd, $rs, $rt"},
	{IT_reg, "MADDU", "$rd, $rs, $rt"},
	{IT_reg, "MADDU1", "$rd, $rs, $rt"},
	{IT_reg, "MFHI1", "$rd"},
	{IT_reg, "MFLO1", "$rd"},
	{IT_reg, "MFSA", "$rd"},
	{IT_reg, "MTHI1", "$rs"},
	{IT_reg, "MTLO1", "$rs"},
	{IT_reg, "MTSA", "$rs"},
	{IT_imm, "MTSAB", "$rs, #im"},
	{IT_imm, "MTSAH", "$rs, #im"},
	{IT_reg, "MULT1", "$rs, $rt"},
	{IT_reg, "MULTU1", "$rs, $rt"},
	{IT_reg, "PABSH", "$rd, $rt"},
	{IT_reg, "PABSW", "$rd, $rt"},
	{IT_reg, "PADDB", "$rd, $rs, $rt"},
	{IT_reg, "PADDH", "$rd, $rs, $rt"},
	{IT_reg, "PADDSB", "$rd, $rs, $rt"},
	{IT_reg, "PADDSH", "$rd, $rs, $rt"},
	{IT_reg, "PADDSW", "$rd, $rs, $rt"},
	{IT_reg, "PADDUB", "$rd, $rs, $rt"},
	{IT_reg, "PADDUH", "$rd, $rs, $rt"},
	{IT_reg, "PADDUW", "$rd, $rs, $rt"},
	{IT_reg, "PADDW", "$rd, $rs, $rt"},
	{IT_reg, "PADSBH", "$rd, $rs, $rt"},
	{IT_reg, "PAND", "$rd, $rs, $rt"},
	{IT_reg, "PCEQB", "$rd, $rs, $rt"},
	{IT_reg, "PCEQH", "$rd, $rs, $rt"},
	{IT_reg, "PCEQW", "$rd, $rs, $rt"},
	{IT_reg, "PCGTB", "$rd, $rs, $rt"},
	{IT_reg, "PCGTH", "$rd, $rs, $rt"},
	{IT_reg, "PCGTW", "$rd, $rs, $rt"},
	{IT_reg, "PCPYH", "$rd, $rs, $rt"},
	{IT_reg, "PCPYLD", "$rd, $rs, $rt"},
	{IT_reg, "PCPYUD", "$rd, $rs, $rt"},
	{IT_reg, "PDIVBW", "$rs, $rt"},
	{IT_reg, "PDIVUW", "$rs, $rt"},
	{IT_reg, "PDIVW", "$rs, $rt"},
	{IT_reg, "PEXCH", "$rd, $rt"},
	{IT_reg, "PEXCW", "$rd, $rt"},
	{IT_reg, "PEXEH", "$rd, $rt"},
	{IT_reg, "PEXEW", "$rd, $rt"},
	{IT_reg, "PEXT5", "$rd, $rt"},
	{IT_reg, "PEXTLB", "$rd, $rs, $rt"},
	{IT_reg, "PEXTLH", "$rd, $rs, $rt"},
	{IT_reg, "PEXTLW", "$rd, $rs, $rt"},
	{IT_reg, "PEXTUB", "$rd, $rs, $rt"},
	{IT_reg, "PEXTUH", "$rd, $rs, $rt"},
	{IT_reg, "PEXTUW", "$rd, $rs, $rt"},
	{IT_reg, "PHMADH", "$rd, $rs, $rt"},
	{IT_reg, "PHMSBH", "$rd, $rs, $rt"},
	{IT_reg, "PINTEH", "$rd, $rs, $rt"},
	{IT_reg, "PINTH", "$rd, $rs, $rt"},
	{IT_reg, "PLZCW", "$rd, $rs"},
	{IT_reg, "PMADDH", "$rd, $rs, $rt"},
	{IT_reg, "PMADDUW", "$rd, $rs, $rt"},
	{IT_reg, "PMADDW", "$rd, $rs, $rt"},
	{IT_reg, "PMAXH", "$rd, $rs, $rt"},
	{IT_reg, "PMAXW", "$rd, $rs, $rt"},
	{IT_reg, "PMFHI", "$rd"},
	{IT_reg, "PMFHL.LW", "$rd"},
	{IT_reg, "PMFHL.UW", "$rd"},
	{IT_reg, "PMFHL.SLW", "$rd"},
	{IT_reg, "PMFHL.LH", "$rd"},
	{IT_reg, "PMFHL.SH", "$rd"},
	{IT_reg, "PMFLO", "$rd"},
	{IT_reg, "PMINH", "$rd, $rs, $rt"},
	{IT_reg, "PMINW", "$rd, $rs, $rt"},
	{IT_reg, "PMSUBH", "$rd, $rs, $rt"},
	{IT_reg, "PMSUBW", "$rd, $rs, $rt"},
	{IT_reg, "PMTHI", "$rs"},
	{IT_reg, "PMTHL.LW", "$rs"},
	{IT_reg, "PMTLO", "$rd, $rs, $rt"},
	{IT_reg, "PMULTH", "$rd, $rs, $rt"},
	{IT_reg, "PMULTUW", "$rd, $rs, $rt"},
	{IT_reg, "PMULTW", "$rd, $rs, $rt"},
	{IT_reg, "PNOR", "$rd, $rs, $rt"},
	{IT_reg, "POR", "$rd, $rs, $rt"},
	{IT_reg, "PPAC5", "$rd, $rt"},
	{IT_reg, "PPACB", "$rd, $rs, $rt"},
	{IT_reg, "PPACH", "$rd, $rs, $rt"},
	{IT_reg, "PPACW", "$rd, $rs, $rt"},
	{IT_reg, "PREVH", "$rd, $rt"},
	{IT_reg, "PROT3W", "$rd, $rt"},
	{IT_reg, "PSLLH", "$rs, $rt, %sa"},
	{IT_reg, "PSLLVW", "$rd, $rs, $rt"},
	{IT_reg, "PSLLW", "$rs, $rt, %sa"},
	{IT_reg, "PSRAH", "$rs, $rt, %sa"},
	{IT_reg, "PSRAVW", "$rd, $rs, $rt"},
	{IT_reg, "PSRAW", "$rs, $rt, %sa"},
	{IT_reg, "PSRLH", "$rs, $rt, %sa"},
	{IT_reg, "PSRLVW", "$rd, $rs, $rt"},
	{IT_reg, "PSRLW", "$rs, $rt, %sa"},
	{IT_reg, "PSUBB", "$rd, $rs, $rt"},
	{IT_reg, "PSUBH", "$rd, $rs, $rt"},
	{IT_reg, "PSUBSB", "$rd, $rs, $rt"},
	{IT_reg, "PSUBSH", "$rd, $rs, $rt"},
	{IT_reg, "PSUBSW", "$rd, $rs, $rt"},
	{IT_reg, "PSUBUB", "$rd, $rs, $rt"},
	{IT_reg, "PSUBUH", "$rd, $rs, $rt"},
	{IT_reg, "PSUBUW", "$rd, $rs, $rt"},
	{IT_reg, "PSUBW", "$rd, $rs, $rt"},
	{IT_reg, "PXOR", "$rd, $rs, $rt"},
	{IT_reg, "QFSRV", "$rd, $rt"},
	{IT_imm, "SQ", "$rt, #im($rs)"},
	{IT_imma, "BC0F", "%im"},
	{IT_imma, "BC0FL", "%im"},
	{IT_imma, "BC0T", "%im"},
	{IT_imma, "BC0TL", "%im"},
	{IT_imma, "CACHE", "$rt, %im($rs)"},
	{IT_reg, "DI", "_"},
	{IT_reg, "EI", "_"},
	{IT_reg, "ERET", "_"},
	{IT_reg, "MFBPC", "$rt"},
	{IT_reg, "MFC0", "$rt, ^rd"},
	{IT_reg, "MFDAB", "$rt"},
	{IT_reg, "MFDABM", "$rt"},
	{IT_reg, "MFDVB", "$rt"},
	{IT_reg, "MFDVBM", "$rt"},
	{IT_reg, "MFIAB", "$rt"},
	{IT_reg, "MFIABM", "$rt"},
	{IT_reg, "MFPC", "$rt"},
	{IT_reg, "MFPS", "$rt"},
	{IT_reg, "MTBPC", "$rt"},
	{IT_reg, "MTC0", "$rt, ^rd"},
	{IT_reg, "MTDAB", "$rt"},
	{IT_reg, "MTDABM", "$rt"},
	{IT_reg, "MTDVB", "$rt"},
	{IT_reg, "MTDVBM", "$rt"},
	{IT_reg, "MTIAB", "$rt"},
	{IT_reg, "MTIABM", "$rt"},
	{IT_reg, "MTPC", "$rt"},
	{IT_reg, "MTPS", "$rt"},
	{IT_reg, "TLBP", "_"},
	{IT_reg, "TLBR", "_"},
	{IT_reg, "TLBWI", "_"},
	{IT_reg, "TLBWR", "_"},
	{IT_regf, "ABS.S", "@fd, @fs"},
	{IT_regf, "ABS.D", "@fd, @fs"},
	{IT_regf, "ADD.S", "@fd, @fs, @ft"},
	{IT_regf, "ADD.D", "@fd, @fs, @ft"},
	{IT_imma, "BC1F", "&im"},
	{IT_imma, "BC1T", "&im"},
	{IT_regf, "C.F.S", "@fs, @ft"},
	{IT_regf, "C.F.D", "@fs, @ft"},
	{IT_regf, "C.UN.S", "@fs, @ft"},
	{IT_regf, "C.UN.D", "@fs, @ft"},
	{IT_regf, "C.EQ.S", "@fs, @ft"},
	{IT_regf, "C.EQ.D", "@fs, @ft"},
	{IT_regf, "C.UEQ.S", "@fs, @ft"},
	{IT_regf, "C.UEQ.D", "@fs, @ft"},
	{IT_regf, "C.OLT.S", "@fs, @ft"},
	{IT_regf, "C.OLT.D", "@fs, @ft"},
	{IT_regf, "C.ULT.S", "@fs, @ft"},
	{IT_regf, "C.ULT.D", "@fs, @ft"},
	{IT_regf, "C.OLE.S", "@fs, @ft"},
	{IT_regf, "C.OLE.D", "@fs, @ft"},
	{IT_regf, "C.ULE.S", "@fs, @ft"},
	{IT_regf, "C.ULE.D", "@fs, @ft"},
	{IT_regf, "C.SF.S", "@fs, @ft"},
	{IT_regf, "C.SF.D", "@fs, @ft"},
	{IT_regf, "C.NGLE.S", "@fs, @ft"},
	{IT_regf, "C.NGLE.D", "@fs, @ft"},
	{IT_regf, "C.SEQ.S", "@fs, @ft"},
	{IT_regf, "C.SEQ.D", "@fs, @ft"},
	{IT_regf, "C.NGL.S", "@fs, @ft"},
	{IT_regf, "C.NGL.D", "@fs, @ft"},
	{IT_regf, "C.LT.S", "@fs, @ft"},
	{IT_regf, "C.LT.D", "@fs, @ft"},
	{IT_regf, "C.NGE.S", "@fs, @ft"},
	{IT_regf, "C.NGE.D", "@fs, @ft"},
	{IT_regf, "C.LE.S", "@fs, @ft"},
	{IT_regf, "C.LE.D", "@fs, @ft"},
	{IT_regf, "C.NGT.S", "@fs, @ft"},
	{IT_regf, "C.NGT.D", "@fs, @ft"},
	{IT_regf, "CEIL.L.S", "@fd, @fs"},
	{IT_regf, "CEIL.L.D", "@fd, @fs"},
	{IT_regf, "CEIL.W.S", "@fd, @fs"},
	{IT_regf, "CEIL.W.D", "@fd, @fs"},
	{IT_reg, "CFC1", "$rt, ^rd"},
	{IT_reg, "CTC1", "$rt, ^rd"},
	{IT_regf, "CVT.D.S", "@fd, @fs"},
	{IT_regf, "CVT.D.W", "@fd, @fs"},
	{IT_regf, "CVT.D.L", "@fd, @fs"},
	{IT_regf, "CVT.L.D", "@fd, @fs"},
	{IT_regf, "CVT.L.S", "@fd, @fs"},
	{IT_regf, "CVT.S.D", "@fd, @fs"},
	{IT_regf, "CVT.S.W", "@fd, @fs"},
	{IT_regf, "CVT.S.L", "@fd, @fs"},
	{IT_regf, "CVT.W.S", "@fd, @fs"},
	{IT_regf, "CVT.W.D", "@fd, @fs"},
	{IT_regf, "DIV.S", "@fd, @fs, @ft"},
	{IT_regf, "DIV.D", "@fd, @fs, @ft"},
	{IT_reg, "DMFC1", "$rt, @rd"},
	{IT_reg, "DMTC1", "$rt, @rd"},
	{IT_regf, "FLOOR.L.S", "@fd, @fs"},
	{IT_regf, "FLOOR.L.D", "@fd, @fs"},
	{IT_regf, "FLOOR.W.S", "@fd, @fs"},
	{IT_regf, "FLOOR.W.D", "@fd, @fs"},
	{IT_imm, "LDC1", "@rt, #im($rs)"},
	{IT_imm, "LWC1", "@rt, #im($rs)"},
	{IT_reg, "MFC1", "$rt, @rd"},
	{IT_regf, "MOV.S", "@fd, @fs"},
	{IT_regf, "MOV.D", "@fd, @fs"},
	{IT_reg, "MTC1", "$rt, @rd"},
	{IT_regf, "MUL.S", "@fd, @fs, @ft"},
	{IT_regf, "MUL.D", "@fd, @fs, @ft"},
	{IT_regf, "NEG.S", "@fd, @fs"},
	{IT_regf, "NEG.D", "@fd, @fs"},
	{IT_regf, "ROUND.L.S", "@fd, @fs"},
	{IT_regf, "ROUND.L.D", "@fd, @fs"},
	{IT_regf, "ROUND.W.S", "@fd, @fs"},
	{IT_regf, "ROUND.W.D", "@fd, @fs"},
	{IT_imm, "SDC1", "@rt, #im($rs)"},
	{IT_regf, "SQRT.S", "@fd, @fs"},
	{IT_regf, "SQRT.D", "@fd, @fs"},
	{IT_regf, "SUB.S", "@fd, @fs, @ft"},
	{IT_regf, "SUB.D", "@fd, @fs, @ft"},
	{IT_imm, "SWC1", "@rt, #im($rs)"},
	{IT_regf, "TRUNC.L.S", "@fd, @fs"},
	{IT_regf, "TRUNC.L.D", "@fd, @fs"},
	{IT_regf, "TRUNC.W.S", "@fd, @fs"},
	{IT_regf, "TRUNC.W.D", "@fd, @fs"},
	{IT_nop, "NOP", "_"},  // Alias of SLL zero, zero, 0
};